server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    username: admin
    password: admin
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml